// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Knight":return img`
.......bbb......
......c511b.....
......5fff1.....
......c5f5b.....
......c4f5b.....
......cc4cb.....
....cb1eeedcb...
...ccbd1dddccb..
...deeddddbeed..
....bcdddddcb...
....ccdbdddcc...
....bebbbdbeb...
....ceceeeecc...
....cceccbccc...
......ebdbb.....
......bddbb.....
......ddddb.....
......dddcb.....
......cddcd.....
......bb.bb.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Idle":
            case "anim2":return [img`
......bbb.......
.....c511b......
.....5fff1......
.....c5f5b......
.....c4f5b......
.....cc4cb......
...cb1eeedcb....
..ccbd1dddccb...
..deeddddbeed...
...bcdddddcb....
...ccdbdddcc....
...bebbbdbeb....
...ceceeeecc....
...cceccbccc....
.....ebdbb......
.....bddbb......
.....ddddb......
.....dddcb......
.....cddcd......
.....bb.bb......
................
`, img`
......bbb.......
.....c511b......
.....5fff1......
.....c5f5b......
.....c4f5b......
...cbcc4cbcb....
..ccb1eeedccb...
..deed1dddeed...
...bcddddbcb....
...ccdddddcc....
...bedbdddeb....
...cebbbdbcc....
...ccceeeecc....
.....eccbc......
.....ebdbb......
.....bddbb......
.....ddddb......
.....dddcb......
.....cddcd......
.....bb.bb......
................
`, img`
................
......bbb.......
.....c511b......
.....5fff1......
.....c5f5b......
.....c4f5b......
...cbcc4cb......
..ccb1eeedcb....
..deed1dddccb...
...bcddddbeed...
...ccdddddcb....
...bedbdddcc....
...cebbbdbeb....
...ccceeeecc....
.....eccbccc....
.....ebdbb......
.....bddbb......
.....ddddb......
.....dddcb......
.....cddcd......
.....bb.bb......
`];
            case "WalkingLeft":
            case "anim1":return [img`
................
......bbb.......
.....c555b......
.....ffff5......
.....c5f5b......
.....c4f5b......
.....cc4bb......
....cb1eeedcb...
...ccbd1dddcccb.
...deeddddbeecc.
...bc.ddbbb..eb.
...cc.dbbbb..cc.
...be.bbbbb..cc.
...ce.ceeee.....
...ce.bdcbc.....
.....bdd.bb.....
.....ddd.bb.....
......ddddb.....
......cddcb.....
......bb.cd.....
.........bb.....
................
`, img`
................
......bbb.......
.....c511b......
.....ffff1......
.....c5f5b......
.....c4f5b......
.....cc4bb......
.....b1eeedcb...
....cbd1dddccb..
.....ebbddbeed..
.....bbbbddcb...
.....cbbbbdcc...
....bcbbbbbeb...
....ccceeeecc...
......eccbbcc...
......ebdd......
......bddddd....
......dbbdcc....
......dbbbbd....
......cd........
......bb........
................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
