namespace SpriteKind {
    export const Weapon = SpriteKind.create()
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
tiles.setCurrentTilemap(tilemap`level1`)
let Knight = sprites.create(assets.image`Knight`, SpriteKind.Player)
Knight.setPosition(20, 80)
scene.cameraFollowSprite(Knight)
controller.moveSprite(Knight, 50, 10)
animation.runImageAnimation(
Knight,
assets.animation`Idle`,
200,
true
)
Knight.setBounceOnWall(true)
let Sword = sprites.create(img`
    . . . . . . . . 
    . . . . . . . . 
    . . . . . . . . 
    . . . . . . . . 
    . . . . 1 . . . 
    . . . 1 d d . . 
    . . . d c d . . 
    . . . d b d . . 
    . . . d b d . . 
    . . . d b b . . 
    . . . d b b . . 
    . . . b b b . . 
    . . . b c b . . 
    . . . c c c . . 
    . . . . b . . . 
    . . . . e . . . 
    `, SpriteKind.Weapon)
Sword.setPosition(77, 75)
forever(function () {
    Knight.vy += 2.5
    Knight.setStayInScreen(true)
    animation.runImageAnimation(
    Knight,
    assets.animation`Idle`,
    200,
    true
    )
    if (controller.left.isPressed()) {
        animation.runImageAnimation(
        Knight,
        assets.animation`WalkingLeft`,
        200,
        true
        )
        pause(250)
    } else {
        animation.runImageAnimation(
        Knight,
        assets.animation`Idle`,
        200,
        true
        )
    }
    if (controller.right.isPressed()) {
        animation.runImageAnimation(
        Knight,
        [img`
            ................
            .......bbb......
            ......b555c.....
            ......5ffff.....
            ......b5f5c.....
            ......b5f4c.....
            ......bb4cc.....
            ...bcdeee1bc....
            .bcccddd1dbcc...
            .cceebddddeed...
            .be..bbbdd.cb...
            .cc..bbbbd.cc...
            .cc..bbbbb.eb...
            .....eeeec.ec...
            .....cbcdb.ec...
            .....bb.ddb.....
            .....bb.ddd.....
            .....bdddd......
            .....bcddc......
            .....dc.bb......
            .....bb.........
            ................
            `,img`
            ................
            .......bbb......
            ......b115c.....
            ......1ffff.....
            ......b5f5c.....
            ......b5f4c.....
            ......bb4cc.....
            ...bcdeee1b.....
            ..bccddd1dbc....
            ..deebddbbe.....
            ...bcddbbbb.....
            ...ccdbbbbc.....
            ...bebbbbbcb....
            ...cceeeeccc....
            ...ccbbcce......
            ......ddbe......
            ....dddddb......
            ....ccdbbd......
            ....dbbbbd......
            ........dc......
            ........bb......
            ................
            `],
        200,
        true
        )
        pause(250)
    } else {
        animation.runImageAnimation(
        Knight,
        assets.animation`Idle`,
        200,
        true
        )
    }
    if (controller.anyButton.isPressed()) {
        animation.runImageAnimation(
        Knight,
        assets.animation`Idle`,
        200,
        true
        )
    }
})
